version: '3'

services:

  monitor:
    build: ./
    container_name: ${CONTAINER_NAME}
    restart: always
    hostname: ${HOSTNAME}
    volumes:
          - ${SERVER_PATH}:/home/monitor/
    command: sh -c "/home/monitor/bin/monitor -workdir /home/monitor/config/"